Update bin/feed-data

diff --git a/bin/feed-data b/bin/feed-data
--- a/bin/feed-data
+++ b/bin/feed-data
@@ -1,9 +1,29 @@
 #!/bin/bash
 
-docker exec -it data01 datasync base
-docker exec -it data01 datasync updates
-docker exec -it data01 datasync puppetlabs-products
-docker exec -it data01 datasync puppetlabs-deps
-docker exec -it data01 datasync epel
-docker exec -it data01 datasync misc
-docker exec -it data01 datasync coreos
+#-----------------------------------------------------------------------------
+# Globals:
+#-----------------------------------------------------------------------------
+
+E_BAD_SYNC=1
+
+#------------------------------------------------------------------------------
+# Source miscellaneous bash functions:
+#------------------------------------------------------------------------------
+
+source ./bin/misclib.sh
+
+#------------------------------------------------------------------------------
+# Synchronize all the data:
+#------------------------------------------------------------------------------
+
+for i in base updates puppetlabs-products puppetlabs-deps epel misc coreos; do
+  msg="Synchronizing '${i}' data..."
+  misc::stat_busy "${msg}"
+  if ! docker exec -it data01 datasync ${i} >> /tmp/booddies; then
+    misc::log "[ERROR] ${msg}"
+    misc::stat_fail
+    exit "${E_BAD_SYNC}"
+  else
+    misc::stat_done
+  fi
+done
