Update bin/feed-gito

diff --git a/bin/feed-gito b/bin/feed-gito
--- a/bin/feed-gito
+++ b/bin/feed-gito
@@ -1,34 +1,66 @@
 #!/bin/bash
 
-array1=( 'Puppet config repository' 'Configurations' 'true' 'https://github.com/h0tbird/puppet-config.git' )
-array2=( 'Mesos config repository' 'Configurations' 'true' 'https://github.com/h0tbird/coreos-mesos.git' )
-array3=( 'KVM control repository' 'R10K' 'true' 'https://github.com/h0tbird/r10k-kvm.git' )
-array4=( 'Puppet KVM role repository' 'Puppet roles' 'true' 'https://github.com/h0tbird/puppet-r_kvm.git' )
-array5=( 'Puppet base role repository' 'Puppet roles' 'true' 'https://github.com/h0tbird/puppet-r_base.git' )
-array6=( 'Puppet ssh profile repository' 'Puppet profiles' 'true' 'https://github.com/h0tbird/puppet-p_ssh.git' )
-array7=( 'Puppet misclib module repository' 'Puppet modules' 'true' 'https://github.com/h0tbird/puppet-m_misclib.git' )
-array8=( 'Puppet users module repository' 'Puppet modules' 'true' 'https://github.com/h0tbird/puppet-m_users.git' )
-array9=( 'Puppet ssh module repository' 'Puppet modules' 'true' 'https://github.com/h0tbird/puppet-m_ssh.git' )
-array10=( 'Puppet terminfo module repository' 'Puppet modules' 'true' 'https://github.com/h0tbird/puppet-m_terminfo.git' )
-array11=( 'Puppet stdlib module repository' 'Puppet modules' 'false' 'https://github.com/puppetlabs/puppetlabs-stdlib.git' 'puppet-m_stdlib' )
+#------------------------------------------------------------------------------
+# Globals:
+#------------------------------------------------------------------------------
 
-for i in `seq 11`; do
+# Settings:
+declare -rA REPOS=(
+['https://github.com/h0tbird/puppet-config.git']='Puppet config repository','Configurations','true'
+['https://github.com/h0tbird/coreos-mesos.git']='Mesos config repository','Configurations','true'
+['https://github.com/h0tbird/r10k-kvm.git']='KVM control repository','R10K','true'
+['https://github.com/h0tbird/puppet-r_kvm.git']='Puppet KVM role repository','Puppet roles','true'
+['https://github.com/h0tbird/puppet-r_base.git']='Puppet base role repository','Puppet roles','true'
+['https://github.com/h0tbird/puppet-p_ssh.git']='Puppet ssh profile repository','Puppet profiles','true'
+['https://github.com/h0tbird/puppet-m_misclib.git']='Puppet misclib module repository','Puppet modules','true'
+['https://github.com/h0tbird/puppet-m_users.git']='Puppet users module repository','Puppet modules','true'
+['https://github.com/h0tbird/puppet-m_ssh.git']='Puppet ssh module repository','Puppet modules','true'
+['https://github.com/h0tbird/puppet-m_terminfo.git']='Puppet terminfo module repository','Puppet modules','true'
+['https://github.com/puppetlabs/puppetlabs-stdlib.git']='Puppet stdlib module repository','Puppet modules','false','puppet-m_stdlib')
+declare LOG_FILE='/tmp/booddies.log'
 
-  eval desc=\${array${i}[0]}
-  eval cat=\${array${i}[1]}
-  eval mirror=\${array${i}[2]}
-  eval repo=\${array${i}[3]}
-  eval name=\${array${i}[4]}
+# Return codes:
+readonly E_BAD_CMD=10
+readonly E_BAD_SYNC=11
 
-  echo -e "\n:::: $desc ::::\n"
+# Commands:
+readonly CMD_DOCKER=$(type -P docker); [ -z "${CMD_DOCKER}" ] && exit ${E_BAD_CMD}
 
-  docker exec -it gito01 gitosync \
+#-----------------------------------------------------------------------------
+# Source miscellaneous bash functions:
+#-----------------------------------------------------------------------------
+
+source ./bin/misclib.sh
+
+#----------------------------------------------------------------------------
+# Fork all repositories:
+#----------------------------------------------------------------------------
+
+IFS=','; for repo in "${!REPOS[@]}"; do
+
+  read -a array <<< "${REPOS["$repo"]}"
+
+  desc=${array[0]}
+  cat=${array[1]}
+  mirror=${array[2]}
+  name=${array[3]}
+
+  msg="Synchronizing '${repo}'..."
+  misc::stat_busy "${msg}"
+
+  if ! ${CMD_DOCKER} exec -it gito01 gitosync \
   --admin admin \
   --owner 'The bootstrapping fellowship' \
   --description "${desc}" \
   --category "${cat}" \
   --repo "${repo}" \
   --mirror "${mirror}" \
-  --name "${name}"
+  --name "${name}" >> ${LOG_FILE}; then
+    misc::log "[ERROR] ${msg}"
+    misc::stat_fail
+    exit "${E_BAD_SYNC}"
+  else
+    misc::stat_done
+  fi
 
 done
