Update feed-regi

diff --git a/bin/feed-regi b/bin/feed-regi
--- a/bin/feed-regi
+++ b/bin/feed-regi
@@ -1,17 +1,12 @@
 #!/bin/bash
 
-#----------------------------------------------------------------------------
+#------------------------------------------------------------------------------
 # Globals:
-#----------------------------------------------------------------------------
+#------------------------------------------------------------------------------
 
 # Settings:
 readonly REGISTRY='regi01:5000'
 readonly LOG_FILE='/tmp/booddies.log'
-readonly IMAGES='
-h0tbird/zookeeper:latest
-mesosphere/mesos-master:0.22.1-1.0.ubuntu1404
-mesosphere/mesos-slave:0.22.1-1.0.ubuntu1404
-mesosphere/marathon:v0.8.2'
 
 # Return codes:
 readonly E_BAD_CMD=10
@@ -23,32 +18,43 @@ readonly E_BAD_PURGE=14
 # Commands:
 readonly CMD_CURL=$(type -P curl); [ -z "${CMD_CURL}" ] && exit ${E_BAD_CMD}
 readonly CMD_DOCKER=$(type -P docker); [ -z "${CMD_DOCKER}" ] && exit ${E_BAD_CMD}
+readonly CMD_JQ=$(type -P jq); [ -z "${CMD_JQ}" ] && exit ${E_BAD_CMD}
 
-#----------------------------------------------------------------------------
+#------------------------------------------------------------------------------
+# Source and verify the configuration:
+#------------------------------------------------------------------------------
+
+[ -f /etc/booddies/regi.conf ] && \
+source /etc/booddies/regi.conf || ${E_BAD_CONF}
+
+[ -z "${IMAGES}" ] && echo 'Ops! IMAGES is not set' && exit ${E_BAD_CONF}
+
+#------------------------------------------------------------------------------
 # Source miscellaneous bash functions:
-#----------------------------------------------------------------------------
+#------------------------------------------------------------------------------
 
 [ -f booddies.sh ] && source booddies.sh
 [ -f ./bin/booddies.sh ] && source ./bin/booddies.sh
 [ -f /etc/booddies/booddies.sh ] && source /etc/booddies/booddies.sh
 
-#---------------------------------------------------------------------------
+#------------------------------------------------------------------------------
 # Seek, pull, tag, push and purge:
-#---------------------------------------------------------------------------
+#------------------------------------------------------------------------------
 
-for img in ${IMAGES}; do
+for IMG in ${IMAGES}; do
 
   #-------
   # Seek:
   #-------
 
-  name=${img#*/}; name=${name%:*}
-  msg="Seeking '${name}/${img#*:}' private image..."
-  misc::stat_busy "${msg}"
+  NAME=${IMG%%:*}; TAG=${IMG#*:}
+  MSG="Seeking '${IMG}' private image..."
+  misc::stat_busy "${MSG}"
 
   if ${CMD_CURL} -sX GET \
-  http://${REGISTRY}/v1/repositories/library/${name}/tags/${img#*:} | \
-  grep -qv 'error'; then
+  http://${REGISTRY}/v2/${NAME}/tags/list | \
+  ${CMD_JQ} ".tags | contains([\"${TAG}\"])" 2> /dev/null | \
+  grep -q 'true'; then
     misc::stat_done
     continue
   else
@@ -59,11 +65,11 @@ for img in ${IMAGES}; do
   # Pull:
   #-------
 
-  msg="Pulling '${img}' image..."
-  misc::stat_busy "${msg}"
+  MSG="Pulling '${IMG}' image..."
+  misc::stat_busy "${MSG}"
 
-  if ! ${CMD_DOCKER} pull ${img} >> ${LOG_FILE}; then
-    misc::log "[ERROR] ${msg}"
+  if ! ${CMD_DOCKER} pull ${IMG} >> ${LOG_FILE}; then
+    misc::log "[ERROR] ${MSG}"
     misc::stat_fail
     exit "${E_BAD_PULL}"
   else
@@ -74,11 +80,11 @@ for img in ${IMAGES}; do
   # Tag:
   #------
 
-  msg="Tagging '${img}' image..."
-  misc::stat_busy "${msg}"
+  MSG="Tagging '${IMG}' image..."
+  misc::stat_busy "${MSG}"
 
-  if ! ${CMD_DOCKER} tag -f ${img} ${REGISTRY}/${img#*/} >> ${LOG_FILE}; then
-    misc::log "[ERROR] ${msg}"
+  if ! ${CMD_DOCKER} tag -f ${IMG} ${REGISTRY}/${IMG} >> ${LOG_FILE}; then
+    misc::log "[ERROR] ${MSG}"
     misc::stat_fail
     exit "${E_BAD_TAG}"
   else
@@ -89,11 +95,11 @@ for img in ${IMAGES}; do
   # Push:
   #-------
 
-  msg="Pushing '${REGISTRY}/${img#*/}' image..."
-  misc::stat_busy "${msg}"
+  MSG="Pushing '${REGISTRY}/${IMG}' image..."
+  misc::stat_busy "${MSG}"
 
-  if ! ${CMD_DOCKER} push ${REGISTRY}/${img#*/} >> ${LOG_FILE}; then
-    misc::log "[ERROR] ${msg}"
+  if ! ${CMD_DOCKER} push ${REGISTRY}/${IMG} >> ${LOG_FILE}; then
+    misc::log "[ERROR] ${MSG}"
     misc::stat_fail
     exit "${E_BAD_PUSH}"
   else
@@ -104,11 +110,11 @@ for img in ${IMAGES}; do
   # Purge:
   #--------
 
-  msg="Purging '${name}/${img#*:}' local image..."
-  misc::stat_busy "${msg}"
+  MSG="Purging '${IMG}' local image..."
+  misc::stat_busy "${MSG}"
 
-  if ! ${CMD_DOCKER} rmi ${img} ${REGISTRY}/${img#*/} >> ${LOG_FILE}; then
-    misc::log "[ERROR] ${msg}"
+  if ! ${CMD_DOCKER} rmi ${IMG} ${REGISTRY}/${IMG} >> ${LOG_FILE}; then
+    misc::log "[ERROR] ${MSG}"
     misc::stat_fail
     exit "${E_BAD_PURGE}"
   else
@@ -116,3 +122,5 @@ for img in ${IMAGES}; do
   fi
 
 done
+
+# vim: set syntax=sh expandtab tabstop=2:
