Update bin/install

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,7 +1,39 @@
 #!/bin/bash
 
+#------------------------------------------------------------------------------
+# Globals:
+#------------------------------------------------------------------------------
+
+E_BAD_SYSTEMCTL=1
+
+#------------------------------------------------------------------------------
+# Source miscellaneous bash functions:
+#------------------------------------------------------------------------------
+
+source ./bin/misclib.sh
+
+#------------------------------------------------------------------------------
+# Install all the services:
+#------------------------------------------------------------------------------
+
 for i in containers/*; do
-  pushd $i
+  pushd $i &> /dev/null
   sudo ./bin/install
-  popd
+  popd &> /dev/null
 done
+
+#------------------------------------------------------------------------------
+# Run 'systemctl daemon-reload'
+#------------------------------------------------------------------------------
+
+msg="Run 'systemctl daemon-reload'"
+
+misc::stat_busy "${msg}"
+
+if ! systemctl daemon-reload; then
+  misc::log "[ERROR] ${msg}"
+  misc::stat_fail
+  exit "${E_BAD_SYSTEMCTL}"
+else
+  misc::stat_done
+fi
